### Correct-number
POST http://localhost:6083/phone-number/send-code
content-type: application/json
Authorization: fake-token

{
  "phoneNumber": "+447430001000"
}

###
POST http://localhost:6083/phone-number/verify-code
content-type: application/json
Authorization: fake-token

{
  "phoneNumber": "+447430001000",
  "passcode": "DAKMHY"
}

### Notification Status
GET http://localhost:6083/phone-number/notifications/ecf20f0a-86af-4ebf-9012-e48bc6a31174
Authorization: fake-token

### Notification Status
GET http://localhost:6083/phone-number/notifications/noresult-d385-4b17-a0b4-23a85c0c5b1a
Authorization: fake-token

### Notification Status
GET http://localhost:6083/phone-number/notifications/systemclock-d385-4b17-a0b4-23a85c0c5b1a
Authorization: fake-token

### Notification Status
GET http://localhost:6083/phone-number/notifications/validation-d385-4b17-a0b4-23a85c0c5b1a
Authorization: fake-token

### Fixed_line
POST http://localhost:6083/phone-number/send-code
content-type: application/json
Authorization: fake-token

{
  "phoneNumber": "02088207098"
}

### Mobile
POST http://localhost:6083/phone-number/send-code
content-type: application/json
Authorization: fake-token

{
  "phoneNumber": "07843274331"
}

### Toll_free
POST http://localhost:6083/phone-number/send-code
content-type: application/json
Authorization: fake-token

{
  "phoneNumber": "0845 46 41"
}

###
POST http://localhost:6083/phone-number/send-code
content-type: application/json
Authorization: fake-token

{
  "phoneNumber": "dfsdsfs"
}

###
POST http://localhost:6083/phone-number/verify-code
content-type: application/json
Authorization: fake-token

{
  "phoneNumber": "07843274331",
  "passcode": "GTHJKL"
}
