### Correct-number
POST http://localhost:6083/customer-insight-platform/phone-number/verify
content-type: application/json

{
  "phoneNumber" : "07843274331"
}

###
POST http://localhost:6083/customer-insight-platform/phone-number/verify
content-type: application/json

{
  "phoneNumber" : "dfsdsfs"
}

### Notification Id
